### ISSUE TITLE
Bug: auth should also check if xsrf token is set in cookies after checking via headers

### ISSUE THREAD

**Issue by c-nv-s** [go-pkgz/auth#109]
https://github.com/go-pkgz/auth/blob/5784dad303c1c1937d694a19f52a878caf5e863b/token/jwt.go#L302

this line seems to suggest that only the header value (default X-XSRF-TOKEN) is checked to see if the token is there.

if the user has not set that header then surely the default cookie value ``defaultXSRFCookieName  = "XSRF-TOKEN"`` should be then checked to see if it set and used?

**Comment by c-nv-s** [comment]
hmm so what's the purpose of setting XSRF-TOKEN cookie if it is never going to be used?
I can see that both JWT and XSRF-TOKEN cookies are set. If I disableXSRF then the authentication works as expected, but with it enabled I receive ``auth failed, can't get token: xsrf mismatch``
I would think that unless you are specifically building an api then the user shouldn't be required to manually set X-XSRF-TOKEN for a web ui? it should just be read from the cookie value

**Comment by umputun** [comment]
XSRF-TOKEN cookie set for the client. Client reads it and expected to send X-XSRF-TOKEN header back

**Comment by c-nv-s** [comment]
aaah I see ok sorry you can close this ticket then

**Comment by ifel** [comment]
> XSRF-TOKEN cookie set for the client. Client reads it and expected to send X-XSRF-TOKEN header back

@umputun is this an "RFC requirement"?

In my current case (I'm integrating the lib with my app), there is no frontend at the moment, I'm trying to login with Facebook and specify the https://domain/auth/status as the "from" URL, so after auth, I'm supposed to get redirected there. Potentially, this is a real world scenario, when all the requests (not just AJAX/API from a frontend) are served by the Go app. So, what happens at the moment, Facebook authorizes me, and then redirects to the URL, which says "unauthorized" because of missing header.

Thus, if there is no "frontend" which sends requests to the backend (and sets the header), the auth does not work and the only way is to disable XSRF (which is insecure, right?).

If that's not an RFC requirement (sorry I did not find an RFC for this), I'd either to add a fallback as @c-nv-s suggested, of added an option (which is false by default to preserve the current behavior), which would enable the cookie check if the option is enabled.

I can code this myself if the idea is ok and it will be then accepted.

**Comment by umputun** [comment]
I'm not sure I get the use case. Do you do auth with some web frontend first and, after this, want to make authorized HTTP calls from another non-web client? In this case, you only need to send auth header (X-JWT by default) in each request, and it won't do any XSRF checks because they don't make sense here. It is not insecure because I don't see how XSRF is even relevant in such direct API calls without a browser involved.

> an option (which is false by default to preserve the current behavior), which would enable the cookie check if the option is enabled.

There is a parameter `DisableXSRF` already, so you can play with this.

**Comment by ifel** [comment]
Well, in fact, I have a react frontend, which will send a request to a backend, will get 403, initiate a login procedure which will redirect to one of the frontend pages, where axios (hopefully) will copy the value from the cookie to the header and will pass it to the backend.

However, imagine this scenario.
```
router.With(m.Auth).Get("/", protectedRouteHandler)
router.With(m.Auth).Get("/private", protectedRouteHandler)

func protectedRouteHandler(...) {
  if user_is_logged {
    return redirect("/private")
  } else {
    return redirect("/auth/provider/login?from=/private")
  }
}
```

In this scenario, the user will receive an error, while they are authorized. Potentially, this maybe a wrong case, as it seems (I'm far away from being an expert in this area), XSRF needs only in case if there is a third component - JS running in the browser. However, in the scenario above, the cookie will be set in the browser after auth. So if there is a UI, apart of the web browser directly accessing some endpoints (BTW, what about avatars?), either UI has to work w/o XSRF (as otherwise direct requests will not be working), or the app should be rewritten not to use the direct requests and do everything thru the UI.

So the use case is - the backend plays a mixed role - an endpoint for AJAX requests from UI and an endpoint for direct requests from the browser.

> DisableXSRF

It's not quite what I meant. I've found it and with its help made auth working for my site.
I meant a flag, which would allow to fallback into checking the cookie if the token is not set in the header should a user wants to use the lib in such a mixed use case.

**Comment by umputun** [comment]
> I meant a flag, which would allow to fallback into checking the cookie if the token is not set in the header should a user wants to use the lib in such a mixed use case.

XSRF check has very little to do with cookie checks and the auth itself. I mean, regardless of XSRF or not it checks the token. This token can be from two places - the cookie or the header.

> So the use case is - the backend plays a mixed role - an endpoint for AJAX requests from UI and an endpoint for direct requests from the browser.

I'm unsure what the difference is between AJAX requests from UI  and direct requests from the browser in this context. What does direct even mean, in this case, access to some static assets? The library is for API auth and won't work like this. Even if all you need is adding a JWT header to the "direct request" this header has to be added by some js code. Generally, the client side should set `X-XSRF-TOKEN` as described above unless you set `DisableXSRF`. `DisableXSRF` doesn't change cookie usage for auth at all. In both cases, your web browser will send jwt server-only cookie back to the server, and the server will do all the checks.

I'm not a JS developer and can't help much with the client side. Maybe @akellbl4 can clarify; he is the expert and used this auth in real systems.

**Comment by ifel** [comment]
> I'm unsure what the difference is between AJAX requests from UI and direct requests from the browser in this context. What does direct even mean, in this case, access to some static assets?

There are 2 things on the client side (I'm talking about a standard web browser, and not a python/go whatever custom app that can talk http):
1. Code running in browser (JS). The key point here, this code prepares HTTP requests itself, so it decides what to send and how. The code can copy values from cookies into headers and vise versa, add or strip key/value pairs into headers or cookies sent to the server as part of the request.
2. Classic html elements that request certain documents from the backends - like <img>, <iframe>, <script>, etc. They do not control what's sent to the server, but a web browser does, and in most of the cases, it does not do any manipulations with headers and cookies like the code above does - it pretty much sends cookies as is, and sets certain headers from its settings.

Now, say I want show an image on a page, but it has to be shown only to auth users. It does not really matter what the page is - a plain html downloaded from the server, or a Dynamic application (React, Angular, etc) at the end of the day they just drop certain elements to the DOM. So, the simplest way to do what I want is to register a route: `router.With(m.Auth).Get("/privateimage", privateImageHandler)`, and add this code to the page: `<img src="/privateimage">`. So, when the web browser starts rendering the page, it will send a request to the server to download the image. 

As it's the case number 2, the request to the server will be sent by the web browser, and not some application running IN the web browser (some JS using the "fetch" function or the "axios" lib), so the value from the cookies will not be copied to the header, and despite the user is authenticated for the rest of the app, this request will fail as unauthorized.
The only way to make it working is to use DisableXSRF which decreases security in general (again, we're talking about the mixed use case, so let's assume some part of the web site makes AJAX requests).

**Comment by umputun** [comment]
So, you are talking about access to some static assets. I don't understand how this mixed model will do anything good in your proposed way. I.e., "allow to fallback into checking the cookie if the token is not set in the header" is not that different from DisableXSRF. If a lack of an XSRF header is allowed by the server for all the endpoints, it means any request, including forged CSRF requests, will be allowed. 

Theoretically, this can be addressed with a list of resources allowed to ignore XSRF completely and not expect the header set by the client. However, this is not what the library currently supports directly.  As I mentioned above, the library was designed for API auth, which enforces all the requests to make XSRF tokens. Excluding some resources from this logic doesn't sound like a good idea, as it opens doors for potential vulnerabilities. 

Probably, you can instantiate two different auth instances on your server - one with proper XSRF support and another with DisableXSRF, and protect your API endpoints with the middleware from the first one and the static assets with the second one.  I have never tried it, but don't see why it won't work.

I don't have a clever idea of achieving what you want from the client side without introducing such "naked" endpoints, but I would expect your js/react side to allow some sort of request interceptor which sets the proper header regardless of how it is sent.

**Comment by XaveScor** [comment]
@ifel Hi, you can create a proxy for all requests on the page with service workers https://stackoverflow.com/questions/60535097/catch-request-in-service-worker-and-respond-with-different-image-url. I think it can help in your case.

**Comment by ifel** [comment]
@umputun thanks for the explanation. It seems now I started understanding the idea behind XSRF (like I wrote originally I'm not quite familiar with its details), and seems this behavior is the key - requiring a client to explicitly copying the value to the header prevents attackers which do not control code from reading data from the backend using "accidental" redirects.

What to the use case (mixed approach) in general, my application is React based, and it uses API from JS, so when I change it completely to use the lib (working on the frontend part now), I will not need to do redirects to the endpoints directly. I brought this as I'd faced this issue when I'd started adopting the backend, and tried to redirect the auth service to one of the known endpoints (/auth/status) to make sure it works. So that's rather a potential use case and not real one, at least for me.

I like your idea about a list of "naked" endpoints, but I clearly understand that the use case I described is uncommon and probably cannot be called a best practice either, but as the implementation will probably require a significant effort, I don't think it worth implementing.

@ XaveScor thanks for the hint.
