### ISSUE TITLE
Give an access to bearer token, aquired during authentication proccess

### ISSUE THREAD

**Issue by boryashkin** [go-pkgz/auth#123]
In provider/oauth2 the AuthHandler func does receive a brearer-token, using which we could pontentially access a private API of identity provider. Wouldn't it be useful? Any concerns about adding some hook for this?
That way go-pkgz/auth will be used as an authorization framework, allowing to setup a proxy to a private API without giving a client any direct access to bearer-token itself.

**Comment by sneat** [comment]
I've hit this issue recently in relation to the Patreon provider. Annoyingly, if you log in with your creator account on Patreon, it automatically refreshes the access and refresh token which then invalidates the existing one's use for "backend" campaign related data.

Having access to the bearer-token returned from Patreon would allow me to update the "backend" access token within the app, and maintain correct access.

**Comment by paskal** [comment]
Something is off in this Patreon situation: OAuth login shouldn't affect temporary credentials you issued for programmatic use elsewhere in their system. Either their system is not working as it should, or you are not using the right type of credentials for that other purpose you're trying to accomplish. Could you please clarify that with their support?

**Comment by sneat** [comment]
@paskal it's 100% Patreon's problem. But they were made aware of it years ago and aren't doing anything about it.

The situation I have is:

1. Create an "API Key" with patreon (it's just a standard OAuth Client ID/Secret/Access/Refresh token).
2. Use the Access Token from the "API key" to be able to access the Patreon API (it needs to be the creator's API access token to be able to access the campaign data, members who have pledged etc).
3. Login via Patreon OAuth with the same account that created the "API key" and Patreon rotates the "API key". There's no way around it.

Now the only options (that I see) left are to:

1. Tell the creator to *never* log into the application via the Patreon OAuth login (hard to achieve as it's the primary "login" in the app - to determine who should have access to what data tiers).
2. Deal with the fact that the access token will change when the creator inevitably logs in via Patreon and update the stored "Creator Access Token" so that the backend can keep working.

Would love to hear any other suggestions to work around the frustration that is Patreon.

**Comment by boryashkin** [comment]
> Giving the ability to manipulate the private key is an attack area this library doesn't want to have

@paskal could you please elaborate on this one? Which private key and who can manipulate?

**Comment by paskal** [comment]
Sorry, I meant the bearer token. Judging by what I know, the library's author made the library in a way where you don't have control over it so that it would be impossible to misuse it.

Giving users control over it increases the library's complexity and opens the possibility of misusing it. So far, the author was not convinced by the arguments in the issues to give that control.

cc @umputun in case you'll want to elaborate on it.

**Comment by sneat** [comment]
Ok, I have a backend system that talks to the Patreon API to keep track of who is a member of the "Campaign" (a Patreon term that basically means who is subscribed to a person - you as a Patreon creator only have a single campaign), what Tier they are subscribed at etc. This allows the backend system to do notifications, processing etc based on who is a member each month and what level they are supporting at (regardless of whether they login on the frontend or not).

The only way for the backend to communicate with the Patreon API is via an "API key" which is configured at https://www.patreon.com/portal/registration/register-clients and is a standard OAuth setup (ClientID, Client Secret setup - it's also the way that you set up the OAuth flow to use with this Auth package). When you create it, you also get a "Creator's token" which is just a standard Access and Refresh token. These tokens have no automatic expiry.

Very annoyingly though, if you authenticate against Patreon using your account that created the ClientID and Client Secret, Patreon revokes the existing Creator Access token and Creator Refresh token (they are no longer valid and any attempt to communicate with the API results in a 403) and a new token is generated (returned as part of the standard OAuth token and also reflected on the https://www.patreon.com/portal/registration/register-clients page details). This [post/thread](https://www.patreondevelopers.com/t/creators-access-token-refreshes-all-the-time/3197/7) back in 2020 also states the same.

So that's the backend side that talks through how the "creator token" gets invalidated. I have no idea why Patreon have decided to implement the auth flow in that way but it doesn't seem like it's going to be changed any time soon.

On the frontend, my client's website has a "Login with Patreon" style button which allows their users to view more details of their content etc. I have an alternate login method for the client but I can't ensure that they will never click on the "Login with Patreon" button and I don't think it's reasonable to say "never click on this button that everyone else uses otherwise you'll break the site". As it is right now, I can know when they have clicked it since I know the creators ID of the Patreon "Campaign" and can match against that - unfortunately by that stage in the flow the "damage is already done" and the only recovery path is to go to https://www.patreon.com/portal/registration/register-clients on the Creator's login, get the new access token and update the value in the Admin (backend) - which is an annoyingly manual process.

By having the access token available at some stage during the auth process, I can detect that it's the Creator who has logged in and update the access token in the backend. I have no need for the refresh token (since the creator token has no expiry anyway).

I understand not wanting to provide any backend implementation access to the user's Access Token (although it's restricted to the Scopes presented to the user during the Auth flow - they are agreeing to providing access to the site to know the details according to the presented scopes). Correct me if I'm wrong, but I'm assuming that's the part that you're wanting to avoid - don't let the backend system operate as though it's the end-user?

I'd be perfectly happy for it not to be a generic implementation that would make the bearer token available to all providers, just for the Patreon provider would be fine (if that's reasonably doable).

I also 100% agree that this shouldn't be the responsibility of this library, but the current implementation effectively rules out being able to use this library for any practical use-case against Patreon (again, entirely Patreon's fault, not this libraries).

Hopefully this explains more of the context and the issue I'm trying to solve - happy to talk through any part of it in more detail if you'd like.

**Comment by boryashkin** [comment]
> The idea of making this API key R/W somehow (you would need to store/update it, right?) makes me nervous, as updating such a sensitive thing inside the library (or via some callback in the application) sounds very dangerous to me.

If we go back to my initial proposal, I just suggested to give out a Token object to an app and keep the rest as it is now.
The logic of storing and updating will be on the app side. How is it worse than just to lose the token after an authentication process?
I suppose your concern is that a user of an app with “oauth2 buttons” may think, that the app will not use any api on his behalf aside the auth process. But when he authenticates, an identity provider usually shows a confirmation pop up with a list of scopes he grants the app with. So no broken expectations here. And no more security concerns, than expected.

The lib has plenty of useful code, but serves as a client auth only. It is written in a manner when injection of a custom code is not possible. So the only way to do it - provide us with hooks, to achieve more complicated logic.
Without the Token hook, i need to write a duplicate of this lib basically. I like the way this lib handles an authentication, but I think it doesn’t allow me to built a complete oauth2 application.

**Comment by umputun** [comment]
>  I just suggested to give out a Token object to an app and keep the rest as it is now.

Thx. I have seen your PR, and it seems reasonable to me. However, I have not reviewed it as it is still in Draft status. If you can finalize it, I'll take a closer look

**Comment by boryashkin** [comment]
> If you can finalize it, I'll take a closer look

Done

**Comment by sneat** [comment]
@umputun are you able to take another look at the PR please?

**Comment by boryashkin** [comment]
@sneat Could you try the code from the main branch? 

The PR is merged, thanks.
